import SwiftUI
import Shared

/// Swift-side type-safe route mirroring the Kotlin `Destination` sealed
/// interface.
///
/// `NavigationStack`'s typed API requires the path element to be `Hashable`.
/// The Kotlin `Destination` protocol generated by K/N is not `Hashable` at
/// the Swift level, so we mirror it with a native enum and provide a
/// converter initializer for interop.
enum Route: Hashable {
    case todoList
    case todoDetail(id: String?)

    init?(from destination: any Destination) {
        if destination is DestinationTodoList {
            self = .todoList
        } else if let detail = destination as? DestinationTodoDetail {
            self = .todoDetail(id: detail.id)
        } else {
            return nil
        }
    }
}

/// Observable navigation coordinator injected into the environment.
///
/// Holds the `NavigationPath` backing a `NavigationStack` and exposes the
/// standard push / pop operations on top of our `Route` enum.
@MainActor
@Observable
final class AppNavigator {
    var path: NavigationPath = NavigationPath()

    func push(_ route: Route) {
        path.append(route)
    }

    /// Convenience: push a Kotlin `Destination` by translating it into a
    /// Swift `Route` first. No-op if the destination cannot be mapped.
    func push(_ destination: any Destination) {
        if let route = Route(from: destination) {
            push(route)
        }
    }

    func pop() {
        if !path.isEmpty { path.removeLast() }
    }
}
